name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Preparre artefact
        run: |
          ls -la -R .next
          mkdir -p ./.next/standalone/.next/

          cp -R public ./.next/standalone/public
          cp -R .next/static ./.next/standalone/.next/static
          cp .env.example ./.next/standalone/.env.example

      - name: Deploy artefact
        uses: actions/upload-artifact@v7
        with:
          name: build-artifact
          path: |
            ./.next/standalone/
          include-hidden-files: true
