name: CI

on:
  push:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run npm audit
        run: npm audit --audit-level=high

  build:
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Preparre artefact
        run: |
          ls -la -R .next
          mkdir -p ./.next/standalone/.next/

          cp -R public ./.next/standalone/public
          cp -R .next/static ./.next/standalone/.next/static
          cp .env.example ./.next/standalone/.env.example

      - name: Deploy artefact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            ./.next/standalone/
